require './migration'
require './recipe'
require './scraper.rb'


namespace :db do 
  
  task :migrate do
    Schema.new.change
  end
  
  task :drop do 
    Schema.new.clear
  end
  
  task :populate do 
    ingredients = %w(boeuf lapin agneau veau fraise framboise pomme fromage miel asperge couteaux bar)
    ingredients.each do |ingredient|
      (1..2).each do |difficulty|
        MarmitonScraper.extract_recipes(ingredient, difficulty).each do |recipe|
          Recipe.create(recipe)
        end
      end
    end
  end
  
  task :clear do 
    Recipe.all.each do |recipe| 
      recipe.destroy
    end
  end
  
end




  